# Generated by Django 4.2 on 2023-05-10 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='sales',
            field=models.FloatField(),
        ),
    ]
